### PR TITLE
Fix SysControl for C++Builder XE4 and some fix to popupmenu

### PR DESCRIPTION
**Pull request by gandf**
Application created with C++Builder XE4 crash on start when
Vcl.Styles.Utils.SysControls is included in project.
Crash is made by this line code. This is due to unpredictable size of
TSysStyleHookClass?
TDictionary<String, TSysStyleHookClass>.Create

### CODE REVIEW

**Comment by gandf** [comment]
1) Improve TVclStylesSystemMenu to automatically list style from "Style"
folder of application
2) always insert separator if requested.

**Comment by gandf** [comment]
Add verticalBar on PopupMenu:
- Draw vertical menu bar with tmPopupSeparator rotated (90°)

**Comment by gandf** [comment]
PopupMenu - keyboard shortcuts are not underlined:
Draw prefix marked by "&"

**Comment by gandf** [comment]
Fix drawing when scroll on larger menu:
This fix work with arrow up and down.
Up and down button are not fixed and not display correctly.

**Comment by gandf** [comment]
Final fix for popupmenu.
All work (scroll, selection, ...) but a flickering are raised when an item are click.
I think we can improve performance but most of the work having been done.

**Comment by RRUZ** [comment]
Thank  you very  much for you contributions. I just merged the commits , but I just keep the changes related to the long popup-menus fix. 
 Some notes 
   1. The _TVclStylesSystemMenu_ is too specific to be included, 
   2. The C++ XE4 related change will be modified and applied in a future version.

Rodrigo.

**Pull request merged**
